### ISSUE TITLE
This project is being shown as excluded project . 

### ISSUE THREAD

**Issue by dhananjay8968** [Shubham56-droid/Hacktoberfest2021_PatternMaking#136]

**Comment by 9m9n** [comment]
Exactly I have also come to this issue. In hacktober show excluded projrct

**Comment by altafshaikh** [comment]
Don't contribute in this repo... excluded from hacktoberfest 2021 event

**Comment by dinesh-kumar-kangani** [comment]
Even for me also it is showing as excluded project
