### ISSUE TITLE
Add  any pattern in  python languages

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/Hacktoberfest2021_PatternMaking#7]
-pls mention name of file with proper extension like .cpp or .py or .java 
-not need to wait to get the task to assign just send PR
-pls follow me and star this repo for successful acceptance of PR
- mention your name in contributing.md

**Comment by nitroidzero** [comment]
please assign me

**Comment by ritikagarg0326** [comment]
please assign this issue to me
